### ISSUE TITLE
Better handling of failed module loading.

### ISSUE THREAD

**Issue by gwsii** [shoreditch-ops/artillery-core#101]
When a plug-in code throws an error, Artillery reports the name of the plug-in as 'unable to load' and continues with the test. This is a problem for a couple of reasons:

1) Assuming the user needed that plug-in to perform testing, attempting to continue is over-optimistic. Artillery should exit at that point and refuse to test.

2) Artillery currently does not show any information about how or why the plug-in could not be loaded, at a minimum if an exception was thrown that message and stack should be reported.

**Comment by hassy** [comment]
I have a PR incoming to address both of these. `artillery-core` itself won't throw/exit but it will return the error information to the caller and leave it up to that code to decide what to do next. In the official CLI that will be print the warning and `process.exit()` but in your serverless code you may want to do something else.
