### ISSUE TITLE
Enhancement Request: match and capture for socket.io emit

### ISSUE THREAD

**Issue by gboysko** [shoreditch-ops/artillery-core#103]
I would like to reuse the `match` and `capture` functionality in a socket.io `emit` flow. I know that the socket.io engine is derived/dependent on the http engine, but I am not sure how reusable those  capabilities are in the socket.io world.

My approach (based on only an introductory review of the code) is to expose `captureOrMatch` from the `engine_http` module. 

Is that a reasonable approach?

**Comment by hassy** [comment]
That would be a good way to start and get it working.

Ideally, we'd extract that function into the `engine_util` module. It takes an HTTP response object as an argument right now, but removing that dependency might be the only change to make the function reusable.

**Comment by gboysko** [comment]
Good suggestion. I'll refactor it to the `engine_util` module. I'm trying to figure out how to debug artillery. I'm trying to figure out the command line to invoke with `node-debug`.

**Comment by hassy** [comment]
I haven't used `node-debug` but can't you run `node-debug bin/artillery`?

**Comment by gboysko** [comment]
It does start up, but it doesn't seem to be resolving the various Git (sub) repos: `artillery-core`, etc. I'm seeing a different code path when I invoke the application that way. How do you debug artillery? Does that (`node-debug .../bin/artillery run test.yml -o foo`) for work you?

**Comment by gboysko** [comment]
FWIW, I have implemented this feature in this pull request: PR #104
