### ISSUE TITLE
Artillery is connecting twice with socket.io

### ISSUE THREAD

**Issue by BerendWeij** [shoreditch-ops/artillery-core#165]
When I run a scenario with socket.io, my 'connection' handler and authentication middleware is being triggered twice (instead of once).

You can test it by using this config:
```
phases:
    - duration: 1
      arrivalRate: 1
```
add a console.log() in your socket.on('connection', () => console.log('connection)). It will be triggered twice instead of once.

**Comment by BerendWeij** [comment]
Weird thing. If you add:
```
socketio:
      query: 'token={"param":value}'
```
you will see the query being part of the second handshake, and not the first.

**Comment by BerendWeij** [comment]
Commenting on my own issue, nice :)

I think it has to do with the methods:

- loadContextSocket (which adds the query to the options) 

- compile (which does **not** add the query to the options)

They both have a io.connect()

**Comment by hassy** [comment]
Sounds like a bug @BerendWeij! Thanks for the report!

**Comment by BerendWeij** [comment]
The issue with the query object is solved with this pull request: https://github.com/shoreditch-ops/artillery-core/pull/170

The double connecting is still occurring unfortunately.

**Comment by BerendWeij** [comment]
I think it is an issue with the namespace.
In the method loadContextSocket, there is a lookup 
```if(!context.sockets[namespace]) {```
If it cannot find a socket, it creates a new one. Which should not be the case.

**Comment by BerendWeij** [comment]
@hassy what would be the easiest way to test changes to artillery-core? I am willing to dive into this issue today when possible. I can find information about the contribution rules, but not about the installation steps.
Best regards!

**Comment by hassy** [comment]
@BerendWeij clone `artillery` and `artillery-core` repos, then point `lib/dispatcher.js` (https://github.com/shoreditch-ops/artillery/blob/master/lib/dispatcher.js) to your local `artillery-core`, `npm install` in both directories, and you're good to go!

**Comment by hassy** [comment]
and thanks for taking a look!

**Comment by BerendWeij** [comment]
Awesome! Thanks for the quick reply. I will keep you posted.

**Comment by dhakan** [comment]
Any news on this? I'm using `artillery 1.6.0-4` and am facing issues with the client connecting twice.  This seems to happen only if I define an emit inside of the `flow` block. Example below:

`{
  "config": {
    "target": "http://localhost:3000",
    "phases": [
      {
        "duration": 1,
        "arrivalRate": 1
      }
    ]
  },
  "scenarios": [
    {
      "engine": "socketio",
      "flow": [
        {
          "emit": {
            "channel": "client-loaded"
          }
        }
      ]
    }
  ]
}`

**Comment by hassy** [comment]
Fixed in `master`, new release on its way.

**Comment by roeycohen** [comment]
there's a problem with this fix.
if you only want to connect and not send anything, it won't connect.

**Comment by hassy** [comment]
Yep, cheers @roeycohen.

**Comment by roeycohen** [comment]
@hassy, but what if i only want to listen?
