### ISSUE TITLE
Known vulnerability in npm dependancy ws.

### ISSUE THREAD

**Issue by RobGruhl** [shoreditch-ops/artillery-core#168]
Module: ws

Issue: DoS due to excessively large websocket message

Overview: ws is a "simple to use, blazing fast and thoroughly tested websocket client, server and console for node.js, up-to-date against RFC-6455" By sending an overly long websocket payload to a ws server, it is possible to crash the node process.

Remediation: Update to version 1.1.1 of ws, or if that is not possible, set the maxpayload option for the ws server - make sure the value is less than 256MB.

References: https://github.com/nodejs/node/issues/7388

**Comment by hassy** [comment]
Should look at updating to a more recent version of `ws` but this particular vulnerability does not apply to Artillery. It's for server-side ws.

**Comment by RobGruhl** [comment]
Yup, just wondering if there's anything we can do to help with versioning upgrades in general.
