### ISSUE TITLE
Expose http response body to afterResponse

### ISSUE THREAD

**Issue by matt-blanchette** [shoreditch-ops/artillery-core#198]
The http response body is only debug logged, 
but it can be useful in afterResponse functions, especially for binary responses.

**Comment by hassy** [comment]
It is available: https://artillery.io/docs/http-reference/#function-signatures - unless you have found a bug where it should be but isn't?

**Comment by matt-blanchette** [comment]
Yes, you are correct, I missed the response.body, Perfect.
