### ISSUE TITLE
default cookies not set

### ISSUE THREAD

**Issue by cyberthom** [shoreditch-ops/artillery-core#35]
Is it intentional that `cookie` set in `defaults` aren't picked up by individual steps?

works:
```javascript
defaults:
  headers:
    cookie: some=value; another=value
```

does not work:
```javascript
defaults:
  cookie:
    some: value
    another: value
```

https://github.com/shoreditch-ops/artillery-core/blob/master/lib/engine_http.js#L59

**Comment by hassy** [comment]
@cyberthom No, that's not intentional and should be considered a bug. A PR would be very gladly received. :balloon:

**Comment by hassy** [comment]
@cyberthom - fix incoming. thanks for helping with the docs btw :+1:

**Comment by cyberthom** [comment]
Ah sorry man - wanted to look into it this weekend. 
Thanks for the fix!

**Comment by hassy** [comment]
@cyberthom no worries!
