### ISSUE TITLE
Perform http & socket.io tasks in 1 flow

### ISSUE THREAD

**Issue by ksplache** [shoreditch-ops/artillery-core#53]
Web applications designed with both http and socket.io often have a sequence of events (i.e. a flow) that requires both http posts, gets, and socket.io calls.  Currently, you can have only one engine per flow so you cannot mix both http and socket.io within a flow.  Example:

```
  "scenarios": [
    {
      "flow": [
        {"post": { "url": "/somepost", "capture": { "json": "$.data", "as": "mydata" } }},
        {"emit": { "channel": "echo", "data": "{{mydata}}", "response": { "channel": "echoed" } }}
        {"think": 1},
      ]
    }
  ]
```

**Comment by ksplache** [comment]
@hassy My proposal for a short term fix is to add the ability for the socket.io engine to delegate steps to the http engine.   I would be comfortable adding that code to the socket.io engine.

A better long term solution might be to allow definition of the engine for each step in the flow, but that seems to be a "big" change to me and not something I can venture into right now.

Let me know if you are OK with the short term approach of delegating from socket.io to http.  The code would be the same as above, with the addition of specifying the engine of ```socketio```

**Comment by hassy** [comment]
Yes, go ahead, that sounds like a good approach for now 👍  Your engine will need to initialise a context to pass into the functions that will handle HTTP actions (see here: https://github.com/shoreditch-ops/artillery-core/blob/master/lib/engine_http.js#L242), but other than that I think it should be pretty straightforward.

I had a think about being able to mix engines freely, but it would indeed be a significant change (maybe even too much to try to make work for any combination of engines).

**Comment by hassy** [comment]
Added in https://github.com/shoreditch-ops/artillery-core/pull/54

**Comment by hassy** [comment]
@ksplache new release: https://github.com/shoreditch-ops/artillery/releases/tag/1.5.0-1

**Comment by lihome** [comment]
i see a httpDelegate in SocketIoEngine. but when i try mix engine to capture some cookie, then
```
TypeError: Cannot read property 'setCookie' of undefined
    at /usr/lib/node_modules/artillery/node_modules/artillery-core/lib/engine_http.js:172:21
    at /usr/lib/node_modules/artillery/node_modules/artillery-core/node_modules/lodash/lodash.js:4411:15
    at baseForOwn (/usr/lib/node_modules/artillery/node_modules/artillery-core/node_modules/lodash/lodash.js:2654:24)

```

**Comment by hassy** [comment]
@lihome can you open a new issue please with a bit more information? (such as what the scenario definition looks like)
