### ISSUE TITLE
socket.io engine does not handle tls option rejectUnauthorized = false

### ISSUE THREAD

**Issue by ksplache** [shoreditch-ops/artillery-core#57]
The tls options from the config object are not being passed to the underlying socket.io connect call.  I'll fix this.

There are also some connect error scenarios that could be handled better.  I'll fix those too.

**Comment by hassy** [comment]
Sounds good 👍

**Comment by hassy** [comment]
Closed by https://github.com/shoreditch-ops/artillery-core/pull/58
