### ISSUE TITLE
A plugin using the "stats" event does not get an event for the last set of requests.

### ISSUE THREAD

**Issue by gwsii** [shoreditch-ops/artillery-core#80]
Comparing the aggregate.latencies.length for the "done" event, it appears that the number of samples is more than what was reported on the "stats" event.

For a plugin that wants to report latencies before the end of the test, using the "stats" event is insufficient as not all of the results will be reported and it will be necessary to handle the "done" event and determine which events have not been recorded/reported.

Or suggestion is that a final "stats" event should be raised during the "done" processing so that the balance of the events which have not been reported via the "stats" event can provided.

**Comment by hassy** [comment]
Fixed in https://github.com/shoreditch-ops/artillery-core/pull/81
