### ISSUE TITLE
socketio response won't match json

### ISSUE THREAD

**Issue by levent** [shoreditch-ops/artillery-core#91]
If my test json looks like this:

`{"emit": { "channel": "echo", "data": "hello", "response": { "channel": "echo", "data": "{\"msg\":\"hello\"}"} }}`

`processResponse` in `engine_socketio.js` seems to fail matching a string with an object even though the debug output looks like it would be a match.

Maybe I'm doing something wrong?

**Comment by hassy** [comment]
@levent thanks for the bug report. I think it's fixed in this PR? https://github.com/shoreditch-ops/artillery-core/pull/90

**Comment by levent** [comment]
@hassy that looks like it'll do it! Will try when I can. Thanks.
